name: Build ebusd configuration

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: tem

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Show installed versions
        run: |
          npm list @ebusd/ebus-typespec @typespec/compiler

      - name: Build German configuration
        run: npm run compile-de

      - name: Upload generated CSV
        uses: actions/upload-artifact@v6
        with:
          name: ebusd-config-de
          path: outcsv.de/
